import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import { isMobileDevice } from "../utils/deviceUtils";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Gubernur Simulator",
  description: "Generated by Dier",
};

const showBannerOnDesktop = true; // Flag untuk toggle pembatas tampilan

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userAgent = (await headers()).get("user-agent") || "";
  const isMobile = isMobileDevice(userAgent);

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        {isMobile || !showBannerOnDesktop ? (
          children
        ) : (
          <div className="flex items-center justify-center min-h-screen">
            <p className="text-center text-lg font-semibold">
              Game ini hanya tersedia di perangkat mobile. jika anda membuka
              <br />
              website melalui ponsel dengan mode desktop view maka silahkan
              matikan dulu
            </p>
          </div>
        )}
      </body>
    </html>
  );
}
